httpSecurity.exceptionHandling()
.accessDeniedPage("/api/accessDenied")
.authenticationEntryPoint(authenticationEntryPoint).and()
.authorizeRequests()
.antMatchers("/guest/**", "/signin/**", "/signup/**").permitAll()
.antMatchers("/user/*")
   .access("hasRole('ROLE_USER') or hasRole('ROLE_ADMIN')")
.antMatchers("/login*").anonymous()
.antMatchers("/admin/*").access("hasRole('ROLE_ADMIN')")
.antMatchers("/api/admin/**").access("hasRole('ROLE_ADMIN') ")
.antMatchers("/api/user/**")
   .access("hasRole('ROLE_ADMIN') or hasRole('ROLE_USER')")
.and().formLogin().loginPage("/#!/login")
.defaultSuccessUrl("/#!/handleSuccessLogin")
.loginProcessingUrl("/perform_login")
.failureHandler(authenticationFailureHandler).and()
.logout().logoutSuccessUrl("/#!/handleSuccesLogout")
.logoutUrl("/user/perform_logout");